name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    name: Build & Test Rust Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Build Rust backend
        run: cargo build --verbose
        working-directory: rust-backend

      - name: Run Rust tests
        run: cargo test --verbose
        working-directory: rust-backend

  frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: backend  # Waits for backend job to finish before running

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: react-frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: react-frontend

      - name: Build frontend
        run: npm run build
        working-directory: react-frontend
